# Generated by Django 2.1.5 on 2019-01-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_auto_20190123_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='question_answer',
        ),
    ]
